### ISSUE TITLE
Ban from BTS

### ISSUE THREAD

**Issue by jasp00** [Debian/README.Debian#15]
Dear Debian community,

Even though I act in good faith, I made a big mistake seven years ago. I am deeply sorry. I hope you would forgive me someday.

Now I am banned from Debian bug tracking system; I do not know why. What have I done wrong? Could anyone guide me?

Thanks for your time and your work.

**Comment by mapreri** [comment]
Seven years ago you were banned from the mailing lists, but not from the BTS.

You've been banned from the BTS only 10 **days** ago, as such I really doubt you don't know why.  Anyway, the reason was "Recent interactions with the BTS have included bug ping-pong and [concern trolling](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837723#49)".

To lift either ban you'll need to convince enough Debian Developers to repeal both decisions.
